/*
 * tools/build.mjs — Tepna
 * Copyright 2026 Michal Planicka
 * SPDX-License-Identifier: Apache-2.0
 * Licensed under the Apache License, Version 2.0. See LICENSE and NOTICE at the
 * project root, or http://www.apache.org/licenses/LICENSE-2.0
 */
/* ════════════════════════════════════════════════════════════════════════
   tools/build.mjs — the Node CLI runner for the owned deterministic bundler
   ────────────────────────────────────────────────────────────────────────
   OWN-THE-BUILD-2026-06-30 Part A (A.1b / A.2). A THIN fs wrapper: it does the
   file IO and delegates ALL transformation + hashing to the dependency-free
   tools/build-core.js — the SAME core the browser driver (tools/build.html /
   the agent's run_script) calls, so agent-built and CI-built bundles are
   byte-identical by construction (the manifest-gate.js dual-runner pattern).

   Commands
     node tools/build.mjs --app OxyDex     build OxyDex.src.html -> OxyDex.html,
                                           update BUILD-MANIFEST + re-stamp that
                                           bundle's code-gated FIXTURE manifestHashes
     node tools/build.mjs --all            build every bundle (fleet migrate)
     node tools/build.mjs --check          READ-ONLY: for every bundle whose committed
                                           .html is already OWNED (plain-inline), rebuild
                                           in memory and diff byte-for-byte; exit 1 on any
                                           drift. Legacy __bundler/manifest bundles are
                                           SKIPPED (not yet migrated) — so --check is green
                                           across the mixed fleet and self-expands as bundles
                                           are cut over. This REPLACES the "did you remember
                                           to re-bundle + update the manifest" human step.

   Ledgers are BUILD OUTPUTS (A.3): a build re-stamps BUILD-MANIFEST.json's manifestHash
   and every code-gated FIXTURE-PROVENANCE.json record for that bundle to the freshly
   computed value. Because plain-inline is deterministic and the migration is EXPORT-INERT
   (no DSP change), a fixture's inputHashes/outputHash do NOT move — only manifestHash. The
   equiv/GATE-C leg in Dex-Test-Suite.html independently proves the committed export is still
   reproduced by current code; if a REAL output change ever rides a build, that leg reds and
   the fixture OUTPUT must be regenerated by re-running the app (never re-stamped blind).

   No npm deps; uses Node built-ins only.
   ════════════════════════════════════════════════════════════════════════ */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const require = createRequire(import.meta.url);
const DexBuild = require(join(__dirname, 'build-core.js'));
const ManifestGate = require(join(ROOT, 'manifest-gate.js'));

const C = { reset: '\x1b[0m', red: '\x1b[31m', green: '\x1b[32m', dim: '\x1b[2m', bold: '\x1b[1m', yellow: '\x1b[33m' };
const paint = (s, c) => (process.stdout.isTTY ? c + s + C.reset : s);
const die = (code, msg) => { console.error(paint('\u2715 ' + msg, C.red)); process.exit(code); };
const BUNDLES = ManifestGate.MANIFEST_BUNDLES;           // single source of the fleet list

function srcFor(bundleFile) { return bundleFile.replace(/\.html$/, '.src.html'); }
const readT = (p) => readFileSync(join(ROOT, p), 'utf8');

// Build ONE bundle in memory: read its .src.html + every referenced asset, hand to the core.
function buildOne(bundleFile) {
  const srcFile = srcFor(bundleFile);
  if (!existsSync(join(ROOT, srcFile))) throw new Error('missing source ' + srcFile);
  const srcHtml = readT(srcFile);
  const refs = DexBuild.scanRefs(srcHtml);
  const assets = {};
  for (const p of [...refs.styles, ...refs.scripts]) {
    if (!existsSync(join(ROOT, p))) throw new Error(srcFile + ' references missing asset ' + p);
    assets[p] = readT(p);
  }
  return DexBuild.build({ srcHtml, assets });          // { html, manifestHash, assetNames }
}

// Re-stamp a bundle's manifestHash into BOTH ledgers (targeted, formatting-preserving string
// replace with count assertions — never a blind JSON.stringify that reflows the whole file).
function restampLedgers(bundleFile, oldHash, newHash) {
  if (oldHash === newHash) return { manifest: 0, fixtures: 0 };
  // BUILD-MANIFEST.json — exactly one occurrence for this bundle's committed hash
  const bmPath = join(ROOT, 'BUILD-MANIFEST.json');
  let bm = readFileSync(bmPath, 'utf8');
  const bmKey = '"manifestHash": "' + oldHash + '"';
  const bmN = bm.split(bmKey).length - 1;
  if (bmN !== 1) throw new Error('BUILD-MANIFEST: expected 1 "' + oldHash + '" for ' + bundleFile + ', found ' + bmN);
  bm = bm.split(bmKey).join('"manifestHash": "' + newHash + '"');
  writeFileSync(bmPath, bm);
  // FIXTURE-PROVENANCE.json — every code-gated fixture of this bundle carries the committed hash.
  const fpPath = join(ROOT, 'FIXTURE-PROVENANCE.json');
  let fp = readFileSync(fpPath, 'utf8');
  const fixtures = (JSON.parse(fp).fixtures) || {};
  const owned = Object.keys(fixtures).filter(k => k[0] !== '_' && fixtures[k] && fixtures[k].bundle === bundleFile && !fixtures[k].historical);
  const want = owned.filter(k => fixtures[k].manifestHash === oldHash).length;
  const fpKey = '"manifestHash": "' + oldHash + '",';
  const fpN = fp.split(fpKey).length - 1;
  if (fpN !== want) throw new Error('FIXTURE-PROVENANCE: expected ' + want + ' code-gated "' + oldHash + '," for ' + bundleFile + ', found ' + fpN);
  if (fpN) { fp = fp.split(fpKey).join('"manifestHash": "' + newHash + '",'); writeFileSync(fpPath, fp); }
  return { manifest: bmN, fixtures: fpN };
}

function committedHash(bundleFile) {
  const bm = JSON.parse(readT('BUILD-MANIFEST.json'));
  return (bm.bundles && bm.bundles[bundleFile] && bm.bundles[bundleFile].manifestHash) || null;
}

function writeBundle(bundleFile) {
  const r = buildOne(bundleFile);
  const old = committedHash(bundleFile);
  writeFileSync(join(ROOT, bundleFile), r.html);
  const stamp = restampLedgers(bundleFile, old, r.manifestHash);
  console.log(paint('  \u2713 ', C.green) + bundleFile + paint('  manifestHash ' + old + ' \u2192 ' + r.manifestHash +
    '  (' + r.html.length + ' bytes, ' + r.assetNames.length + ' assets' +
    (stamp.fixtures ? ', ' + stamp.fixtures + ' fixture(s) re-stamped' : '') + ')', C.dim));
  return r.manifestHash;
}

// READ-ONLY drift check over OWNED bundles only (legacy gzip-pack bundles are skipped).
function check() {
  let drift = 0, checked = 0, skipped = 0;
  console.log(paint('\u25b8 build --check \u2014 committed bundle \u2261 fresh build(source)', C.bold));
  for (const b of BUNDLES) {
    const p = join(ROOT, b);
    if (!existsSync(p)) { console.log(paint('  \u2715 ' + b + ' missing', C.red)); drift++; continue; }
    const committed = readFileSync(p, 'utf8');
    if (!DexBuild.isPlainInline(committed)) { console.log(paint('  \u2218 ' + b + ' legacy __bundler/manifest \u2014 not yet owned, skipped', C.dim)); skipped++; continue; }
    let r; try { r = buildOne(b); } catch (e) { console.log(paint('  \u2715 ' + b + ' build error: ' + e.message, C.red)); drift++; continue; }
    if (r.html === committed) { console.log(paint('  \u2713 ', C.green) + b + paint('  ' + r.manifestHash, C.dim)); checked++; }
    else { console.log(paint('  \u2715 ' + b + ' DRIFT \u2014 committed \u2260 fresh build(' + srcFor(b) + '); re-run `build.mjs --app ' + b.replace(/\.html$/, '') + '`', C.red)); drift++; }
  }
  console.log((drift ? paint('\u2715 ' + drift + ' drift', C.red) : paint('\u2713 clean', C.green)) +
    paint('  (' + checked + ' owned checked, ' + skipped + ' legacy skipped)', C.dim));
  return drift;
}

function main() {
  const argv = process.argv.slice(2);
  const has = (f) => argv.includes(f);
  const appArg = (() => { const i = argv.findIndex(a => a === '--app'); return i >= 0 ? argv[i + 1] : null; })();

  if (has('--check')) { process.exit(check() ? 1 : 0); }

  if (has('--all')) {
    console.log(paint('\u25b8 build --all \u2014 owning every bundle (fleet migrate)', C.bold));
    let n = 0; for (const b of BUNDLES) { writeBundle(b); n++; }
    console.log(paint('\u2713 built ' + n + ' bundle(s). Run `node tests/verify-manifest.mjs` + Dex-Test-Suite.html?full.', C.green));
    process.exit(0);
  }

  if (appArg) {
    const bundleFile = /\.html$/.test(appArg) ? appArg : appArg + '.html';
    if (!BUNDLES.includes(bundleFile)) return die(2, appArg + ' is not a MANIFEST bundle (' + BUNDLES.join(', ') + ')');
    console.log(paint('\u25b8 build --app ' + bundleFile, C.bold));
    writeBundle(bundleFile);
    console.log(paint('\u2713 done. Run `node tests/verify-manifest.mjs` + Dex-Test-Suite.html?full to gate.', C.green));
    process.exit(0);
  }

  console.log('usage: node tools/build.mjs [--check | --all | --app <Name>]');
  process.exit(2);
}

main();
