# GENERATED by tools/derive_edf_dict.py — DO NOT HAND-EDIT.
# Copyright 2026 Michal Planicka · SPDX-License-Identifier: Apache-2.0
"""The AS11 EDF contract, derived from a real card.

Hand-typing this table would make it a pinned-constant oracle: a wrong value would be
agreed with by every test written against it, and the table would DEFEND the bug instead
of catching it. So it is generated, and `--check` fails when the checked-in copy drifts.

⚠️ ONE MACHINE. Every row is [HW] for the card it was derived from and UNVERIFIED for any
other model. A type absent here is absent from that card, not from the format.
"""

SOURCE_CARD = 'cpap'

# name -> record_seconds, signals, and how much evidence stands behind them.
# signals are (label, unit, phys_min, phys_max, dig_min, dig_max, spr) as ASCII, exactly as
# the card writes them — a float round-trip is where a byte-accurate writer stops being one.
TYPES = {
    'BRP': {
        "record_seconds": '60.00',
        "files": 294, "records": 96920, "variants": 1,
        "header_const": {'version': '0', 'header_bytes': '1024', 'reserved': 'EDF'},
        # header fields that differ between files — recorded, never guessed:
        "header_varies": ['patient', 'recording'],
        "signals": (
            ('Flow.40ms', 'L/s', '-2.00', '3.00', '-1000', '1500', '1500'),
            ('Press.40ms', 'cmH2O', '0.00', '40.00', '0', '2000', '1500'),
            ('Crc16', '', '-32768.0', '32767.00', '-32768', '32767', '1'),
        ),
    },
    'CSL': {
        "record_seconds": '0.00',
        "files": 303, "records": 343, "variants": 1,
        "header_const": {'version': '0', 'header_bytes': '768', 'reserved': 'EDF+D'},
        # header fields that differ between files — recorded, never guessed:
        "header_varies": ['patient', 'recording'],
        "signals": (
            ('EDF Annotations', '', '-32768.0', '32767.00', '-32768', '32767', '31'),
            ('Crc16', '', '-32768.0', '32767.00', '-32768', '32767', '1'),
        ),
    },
    'EVE': {
        "record_seconds": '0.00',
        "files": 303, "records": 5581, "variants": 1,
        "header_const": {'version': '0', 'header_bytes': '768', 'reserved': 'EDF+D'},
        # header fields that differ between files — recorded, never guessed:
        "header_varies": ['patient', 'recording'],
        "signals": (
            ('EDF Annotations', '', '-32768.0', '32767.00', '-32768', '32767', '31'),
            ('Crc16', '', '-32768.0', '32767.00', '-32768', '32767', '1'),
        ),
    },
    'PLD': {
        "record_seconds": '60.00',
        "files": 294, "records": 96931, "variants": 1,
        "header_const": {'version': '0', 'header_bytes': '2816', 'reserved': 'EDF'},
        # header fields that differ between files — recorded, never guessed:
        "header_varies": ['patient', 'recording'],
        "signals": (
            ('MaskPress.2s', 'cmH2O', '0.00', '40.00', '0', '2000', '30'),
            ('Press.2s', 'cmH2O', '0.00', '50.00', '0', '2500', '30'),
            ('EprPress.2s', 'cmH2O', '0.00', '30.00', '0', '1500', '30'),
            ('Leak.2s', 'L/s', '0.00', '2.00', '0', '100', '30'),
            ('RespRate.2s', 'bpm', '0.00', '90.00', '0', '450', '30'),
            ('TidVol.2s', 'L', '0.00', '4.00', '0', '200', '30'),
            ('MinVent.2s', 'L/min', '0.00', '30.00', '0', '240', '30'),
            ('Snore.2s', '', '0.00', '5.00', '0', '250', '30'),
            ('FlowLim.2s', '', '0.00', '1.00', '0', '100', '30'),
            ('Crc16', '', '-32768.0', '32767.00', '-32768', '32767', '1'),
        ),
    },
    'SA2': {
        "record_seconds": '60.00',
        "files": 294, "records": 96928, "variants": 1,
        "header_const": {'version': '0', 'header_bytes': '1024', 'reserved': 'EDF'},
        # header fields that differ between files — recorded, never guessed:
        "header_varies": ['patient', 'recording'],
        "signals": (
            ('Pulse.1s', 'bpm', '0.00', '300.00', '0', '300', '60'),
            ('SpO2.1s', '%', '0.00', '100.00', '0', '100', '60'),
            ('Crc16', '', '-32768.0', '32767.00', '-32768', '32767', '1'),
        ),
    },
    'STR': {
        "record_seconds": '86400.00',
        "files": 1, "records": 37, "variants": 1,
        "header_const": {'version': '0', 'patient': 'X X X X 0DF4 D197', 'recording': 'Startdate 29-JUL-2026 X X X SRN=23221590541 MID=46 VID=3', 'header_bytes': '20224', 'reserved': 'EDF'},
        "signals": (
            ('Date', '', '0.00', '24836.00', '0', '24836', '1'),
            ('MaskOn', 'MINUTES', '0.00', '1440.00', '0', '1440', '20'),
            ('MaskOff', 'MINUTES', '0.00', '1440.00', '0', '1440', '20'),
            ('MaskEvents', '', '0.00', '255.00', '0', '255', '1'),
            ('Duration', 'min.', '0.00', '1440.00', '0', '1440', '1'),
            ('Mode', '', '0', '16', '0', '16', '1'),
            ('S.C.StartPress', 'cmH2O', '4.00', '20.00', '200', '1000', '1'),
            ('S.C.Press', 'cmH2O', '4.00', '20.00', '200', '1000', '1'),
            ('S.A.StartPress', 'cmH2O', '4.00', '20.00', '200', '1000', '1'),
            ('S.A.MaxPress', 'cmH2O', '4.00', '20.00', '200', '1000', '1'),
            ('S.A.MinPress', 'cmH2O', '4.00', '20.00', '200', '1000', '1'),
            ('S.AFH.StartPress', 'cmH2O', '4.00', '20.00', '200', '1000', '1'),
            ('S.AFH.MaxPress', 'cmH2O', '4.00', '20.00', '200', '1000', '1'),
            ('S.AFH.MinPress', 'cmH2O', '4.00', '20.00', '200', '1000', '1'),
            ('S.AS.Comfort', '', '0', '16', '0', '16', '1'),
            ('S.RampEnable', '', '0', '16', '0', '16', '1'),
            ('S.RampTime', 'min.', '5.00', '45.00', '5', '45', '1'),
            ('S.EPR.ClinEnable', '', '0', '16', '0', '16', '1'),
            ('S.EPR.EPREnable', '', '0', '16', '0', '16', '1'),
            ('S.EPR.Level', 'cmH2O', '1.00', '3.00', '50', '150', '1'),
            ('S.EPR.EPRType', '', '0', '16', '0', '16', '1'),
            ('S.SmartStart', '', '0', '16', '0', '16', '1'),
            ('S.PtAccess', '', '0', '16', '0', '16', '1'),
            ('S.ABFilter', '', '0', '16', '0', '16', '1'),
            ('S.Mask', '', '0', '16', '0', '16', '1'),
            ('S.Tube', '', '0', '16', '0', '16', '1'),
            ('S.ClimateControl', '', '0', '16', '0', '16', '1'),
            ('S.HumEnable', '', '0', '16', '0', '16', '1'),
            ('S.HumLevel', '', '1.00', '8.00', '1', '8', '1'),
            ('S.TempEnable', '', '0', '16', '0', '16', '1'),
            ('S.Temp', 'Celsius', '15.60', '30.00', '156', '300', '1'),
            ('HeatedTube', '', '0', '16', '0', '16', '1'),
            ('Humidifier', '', '0', '16', '0', '16', '1'),
            ('BlowPress.95', 'cmH2O', '-10.00', '45.00', '-500', '2250', '1'),
            ('BlowPress.5', 'cmH2O', '-10.00', '45.00', '-500', '2250', '1'),
            ('Flow.95', 'L/s', '-2.00', '3.00', '-1000', '1500', '1'),
            ('Flow.5', 'L/s', '-2.00', '3.00', '-1000', '1500', '1'),
            ('BlowFlow.50', 'L/s', '-4.00', '4.00', '-2000', '2000', '1'),
            ('AmbHumidity.50', 'mg/L', '0.00', '100.00', '0', '1000', '1'),
            ('HumTemp.50', 'Celsius', '0.00', '100.00', '0', '1000', '1'),
            ('HTubeTemp.50', 'Celsius', '0.00', '40.00', '0', '400', '1'),
            ('HTubePow.50', '%', '0.00', '100.00', '0', '1000', '1'),
            ('HumPow.50', '%', '0.00', '100.00', '0', '1000', '1'),
            ('SpO2.50', '%', '0.00', '100.00', '0', '100', '1'),
            ('SpO2.95', '%', '0.00', '100.00', '0', '100', '1'),
            ('SpO2.Max', '%', '0.00', '100.00', '0', '100', '1'),
            ('SpO2Thresh', 'min.', '0.00', '1440.00', '0', '1440', '1'),
            ('MaskPress.50', 'cmH2O', '0.00', '40.00', '0', '2000', '1'),
            ('MaskPress.95', 'cmH2O', '0.00', '40.00', '0', '2000', '1'),
            ('MaskPress.Max', 'cmH2O', '0.00', '40.00', '0', '2000', '1'),
            ('TgtIPAP.50', 'cmH2O', '0.00', '50.00', '0', '2500', '1'),
            ('TgtIPAP.95', 'cmH2O', '0.00', '50.00', '0', '2500', '1'),
            ('TgtIPAP.Max', 'cmH2O', '0.00', '50.00', '0', '2500', '1'),
            ('TgtEPAP.50', 'cmH2O', '0.00', '30.00', '0', '1500', '1'),
            ('TgtEPAP.95', 'cmH2O', '0.00', '30.00', '0', '1500', '1'),
            ('TgtEPAP.Max', 'cmH2O', '0.00', '30.00', '0', '1500', '1'),
            ('Leak.50', 'L/s', '0.00', '2.00', '0', '100', '1'),
            ('Leak.95', 'L/s', '0.00', '2.00', '0', '100', '1'),
            ('Leak.70', 'L/s', '0.00', '2.00', '0', '100', '1'),
            ('Leak.Max', 'L/s', '0.00', '2.00', '0', '100', '1'),
            ('MinVent.50', 'L/min', '0.00', '30.00', '0', '240', '1'),
            ('MinVent.95', 'L/min', '0.00', '30.00', '0', '240', '1'),
            ('MinVent.Max', 'L/min', '0.00', '30.00', '0', '240', '1'),
            ('RespRate.50', 'bpm', '0.00', '90.00', '0', '450', '1'),
            ('RespRate.95', 'bpm', '0.00', '90.00', '0', '450', '1'),
            ('RespRate.Max', 'bpm', '0.00', '90.00', '0', '450', '1'),
            ('TidVol.50', 'L', '0.00', '4.00', '0', '200', '1'),
            ('TidVol.95', 'L', '0.00', '4.00', '0', '200', '1'),
            ('TidVol.Max', 'L', '0.00', '4.00', '0', '200', '1'),
            ('AHI', '', '0.00', '240.00', '0', '2400', '1'),
            ('HI', '', '0.00', '240.00', '0', '2400', '1'),
            ('AI', '', '0.00', '240.00', '0', '2400', '1'),
            ('OAI', '', '0.00', '240.00', '0', '2400', '1'),
            ('CAI', '', '0.00', '240.00', '0', '2400', '1'),
            ('UAI', '', '0.00', '240.00', '0', '2400', '1'),
            ('RIN', '', '0.00', '240.00', '0', '2400', '1'),
            ('CSR', '', '0.00', '1440.00', '0', '1440', '1'),
            ('Crc16', '', '-32768.0', '32767.00', '-32768', '32767', '1'),
        ),
    },
}

